version: '3.8'

services:

  php-apache-environment:
    container_name: php-apache
    build:
      context: ./src
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./src/html:/var/www/html/
    ports:
      - 8000:80
    links:
      - db

  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: MYSQL_DATABASE
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    volumes:
      - ./databases:/docker-entrypoint-initdb.d
      - db_volume:/var/lib/mysql
    ports:
      - "9906:3306"

volumes:
  db_volume:

    # version: '3.8'

    # services:
    #   db:
    #     image: mysql:latest
    #     container_name: db
    #     command: --default-authentication-plugin=mysql_native_password
    #     volumes:
    #       - ./databases:/docker-entrypoint-initdb.d
    #       - db_volume:/var/lib/mysql
    #     environment:
    #       - MYSQL_ROOT_PASSWORD=password

    #   php-apache:
    #     build:
    #       context: ./src
    #       dockerfile: Dockerfile
    #     ports:
    #       - "8080:80"
    #     volumes:
    #       - ./src/html:/var/www/html
    #     links:
    #       - db

    # volumes:
    #   db_volume:
