version: '3'

services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./html/:/var/www/html/
      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
    restart: always
    ports:
      - 8000:80
    links:
      - mysql

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./static-html-directory/:/usr/share/nginx/html
    command: [ nginx, '-g', 'daemon off;' ]
    restart: always
    ports:
      - 8080:80
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    links:
      - php

  mysql:
    image: mysql
    restart: always
    environment:
      # MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: mypass
      # MYSQL_PASSWORD: mypass
      # MYSQL_DATABASE: appDB2
    command: [ '--default-authentication-plugin=mysql_native_password' ]
    ports:
      - "9906:3306"
    volumes:
      - ./mysql-init/:/docker-entrypoint-initdb.d/:ro
      - mysql:/var/lib/mysql

volumes:
  mysql:
